version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: wallet-db
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
    ports:
      - "5432:5432"
    volumes:
      - wallet_pg_data:/var/lib/postgresql/data

volumes:
  wallet_pg_data: