spring.application.name=WalletProject
spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_db
spring.datasource.username=wallet_user
spring.datasource.password=wallet_pass
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret = 0AFWE3P4p5xSomcYzFb/B3kivAZOiDhIUaF8UOS9Hxk=
jwt.expiration-ms = 4000000000000
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
