spring.application.name=WalletProject
spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_db
spring.datasource.username=wallet_user
spring.datasource.password=wallet_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
